version: '3'
services:
  db:
    build: .
    container_name: mysql-server
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
