version: '3'
services:
  db:
    build: .
    image: mysql/mysql-db
    container_name: mysql-server
    network_mode: bridge
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql-server-storage:/var/lib/mysql
      - $PWD/temp:/docker-entrypoint-initdb.d



  admin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    network_mode: bridge
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"


volumes:
  mysql-server-storage:
    external: true
